### ISSUE TITLE
Need to add /whatmyIP to REST api?

### ISSUE THREAD

**Issue by BrendanBenshoof** [UrDHT/PyUrDHT#10]
This would allow nodes to have a reliable way to get their external IPs automagically.
I like this option better than using a IP service

**Comment by nwautomator** [comment]
My initial thought here was to traceroute from the node, all the while capturing the output, and looking for the 1st non-private (RFC 1918) address, but that won't work for several reasons
- Some users are on networks whose administrators stupidly block some or all ICMP message types and using raw UDP or TCP traceroutes requires root privileges.
- Some users could be using an ISP which employs carrier-grade NAT, in which case they can't run this code at all.
- This won't work for IPv6 as it doesn't have a meaningful analog to RFC 1918 addresses. Okay, okay, there are ULA addresses, but most users would be using a public IPv6 address their ISP gave them using prefix delegation on their CPE device.
- False positives, false negatives.
- Additional wasted processing time.
- Strange network topologies like several layers of NAT, VPNs, etc...

With that in mind, I think the best solution is to reach out to a peer and have it tell you what your public IP is.

**Comment by BrendanBenshoof** [comment]
Consider yourself volunteered.
essentially all we need is to make every node a little clone of this service: https://www.ipify.org/

**Comment by BrendanBenshoof** [comment]
in fact that has more features than we need. (I'm torn over jsonP, it solves a lot of problems, but makes a lot of new ones)

**Comment by nwautomator** [comment]
This has been merged as part of pull request #19
