### ISSUE TITLE
public node info somehow

### ISSUE THREAD

**Issue by BrendanBenshoof** [UrDHT/PyUrDHT#11]
right now, we assume that if we know the address of a node, we know all the details about it.

we could expose a "/info" command on the REST api to return the node's info json blob.

This also future proofs to let us include information beyond id and path (pub_key ect)

**Comment by nwautomator** [comment]
What sort of info should we expose? My thoughts:
- public IP/port
- version
- public key (if exists)
- uptime
- number of peers
- list of peers
- distance
- anything else?
