### ISSUE TITLE
Casing

### ISSUE THREAD

**Issue by abrosen** [UrDHT/PyUrDHT#14]
Choose either camelcase or _'s and use it.

**Comment by abrosen** [comment]
I'm partial to camelcase

**Comment by abrosen** [comment]
Camelcase is the consensus.
This will be closed when we convert to camelcase.

**Comment by nwautomator** [comment]
This CamelCase or this camelCase?

**Comment by mmcd** [comment]
[this](https://www.python.org/dev/peps/pep-0008/)

**Comment by nwautomator** [comment]
StudlyCaps it is!!  ; )

**Comment by nwautomator** [comment]
Created PR #24  for this.

**Comment by nwautomator** [comment]
This was merged into the LogicCleanup branch as part of PR #24
