### ISSUE TITLE
KISS our names

### ISSUE THREAD

**Issue by abrosen** [UrDHT/PyUrDHT#29]
I love names.  Naming is important, just ask any fantasy author.
We're doing an okay job with descriptive names, however, I think that a couple should be refactored (and I'm happy to do that in my comments branch)

Our first issue is that we suck at spelling.  I can never spell maintenence writ-  maintence right-  sorry maintance- darn it maintenance (there we go) correctly. 
I refactored DHTMaintenceWorker already,, but I think we should change it's name to avoid this issue.  

Perhaps instead of using the -**MaintenanceWorker** suffix, we use **Janitor** and refactor it to DHTJanitor.

loc2PeerTable is also kinda awkward; I dislike using 2 as a shorthand for ''to''

Any objections to me refactoring our names?

**Comment by nwautomator** [comment]
None hear ^H^H^H^H here.  : )
We, along with other folks that may want to use our work, need to be able to read this code in 3 months, 6 months, etc...

**Comment by abrosen** [comment]
I've made the changes in the comments branch.  They'll take effect when we merge.
