### ISSUE TITLE
force-orphan

### ISSUE THREAD

**Issue by mmcd** [UrDHT/PyUrDHT#44]
Noesis:PyUrDHT michael$ python3 main.py 
ping
trying http://45.79.205.125:8000/api/v0/peer/ping
^Cshort []
Node up and Running
set()
{"id":"QmU3wkypfHVtAYHrUsrkya4hPezEghj72SB3514ziqvssd", "addr":"http://131.96.253.63:8000/", "wsAddr":"ws:/131.96.253.63:8001"}
started websocket proxy
short []
set()
short []
set()
short []
set()
short []
set()

**Comment by mmcd** [comment]
see where the control-c is there. go me! TIMING FTW!

**Comment by BrendanBenshoof** [comment]
I'm not sure what just happened? Did you force the ping to fail?

**Comment by mmcd** [comment]
yeah
I think so

**Comment by mmcd** [comment]
I keyboard interrupted something, but it DIDNT kill the python process.

I have no idea how that happens... but it does sometimes

**Comment by nwautomator** [comment]
@mmcd I think you're on a Linux box, so can you run 'script mylog.log' (or whatever you want to call it) to capture your terminal output and try to recreate what you're seeing? Feel free to email to me if you like and I'll take a look.

**Comment by abrosen** [comment]
I'm sorry, what was the issue?

**Comment by BrendanBenshoof** [comment]
It looks like this is os dependent.

Threads + processes are setup as daemon processes (subordinate to the console-attached process) so the os should be taking care of killing them when the host process dies.

I think I am going to close this for now.
