### ISSUE TITLE
so... autosense public ip in python3 snippet

### ISSUE THREAD

**Issue by mmcd** [UrDHT/PyUrDHT#65]
import socket

google = "73.194.219.106"
addrPort = "8000"
wsPort = "8001"

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect((google,80))
ip = s.getsockname()[0]
s.close()

addr = "http://" + ip + ":" + addrPort + "/"
wsAddr = "ws:/" + ip + ":" + wsPort + "/"

print("addr: " + addr)
print("wsAddr: " + wsAddr)

**Comment by BrendanBenshoof** [comment]
we have already solved this via the bootstrap. And this code does not give us an IP if you are behind NAT.

The current default config utilizes it.
