### ISSUE TITLE
models.py

### ISSUE THREAD

**Issue by mmcd** [UrDHT/PyUrDHT#68]
line 334

my IDE is complaining about 'unicode' being an unresolved reference. It also says that it may be allowed due to dynamic dispatch and duck typing. I am just putting things here that I find while I am looking.

**Comment by BrendanBenshoof** [comment]
I can't find this file anywhere in the project?

**Comment by BrendanBenshoof** [comment]
https://github.com/UrDHT/PyUrDHT/blob/32eb90509ca0e608e3108218828fb813e312a492/myrequests/models.py#L334

Looks like a python2 relic. I am going to try changing it to str(arg) which is the proper python3. Interesting that it works anyway.

**Comment by BrendanBenshoof** [comment]
So this is wrapped in a python version check. It is not going to cause us any problems.
