### ISSUE TITLE
Ensure that locPeerDict is populated before seek occurs

### ISSUE THREAD

**Issue by abrosen** [UrDHT/PyUrDHT#77]
In Logic, is it possible that locPeerDict is unpopulated when a seek hits the node?

locPeerDict is populated during maintenance

**Comment by abrosen** [comment]
I'm writing chord to avoid using this Dict

**Comment by BrendanBenshoof** [comment]
yeah, we should pre-populate it on load with the bootstraps.

The reason UrDHT need(ed) it, was that the spacemath file only handled locations, not peerinfo
So I needed to be able to feed queries to spacemath, get a location back as an answer, then map teh location back to the peerinfo.

We would need to re-write spacemath to change how that worked.
